### ISSUE TITLE
[menu] Split resources into sub categories

### ISSUE THREAD

**Issue by olblak** [updatecli/website#189]
## Description
Currently the entry `resources` in the menu, list every available resources. There is no way for visitor to quickly which resource is available for a specific stage.
So it instead of 

* resources
    * githubRelease
    * yaml
    * ...

We would have 

* resources
    * source
        * file
        * githubRelease
    * condition
        * file
        * githubRelease
    * target   
        * file 

---

Of course, the cost of this change would mean documentation duplication.

**Comment by dduportal** [comment]
Duplicating documentation is a good recipe for disaster honestly.

However your ToC proposal makes sense and would add value.

WDYT about the following (dropping the name "resource"):

* Plugins
  * AWS AMI
  * Dockerfile
  ...
  * Shell
* Sources
  * AWS AMI
  ...
* Conditions
...
* Targets
...

?

**Comment by olblak** [comment]
> Duplicating documentation is a good recipe for disaster honestly.
I agree, hence the current implementation but I realise that it's really difficult to identify which resource/plugin can be used for source/condtion/target

Maybe the solution is to only find a way to generate the menu without changing the current site structure.
I wish I could parse every markdown tag to dynamically generate a menh but it doesn't 'seem to be possible.
I need more investigation

**Comment by olblak** [comment]
After some experimentation, it seems that I can use Hugo [taxonomies](https://gohugo.io/content-management/taxonomies/) to get the list of plugins per source/conditions/targets. I am exploring more that path.
